### ISSUE TITLE
Unable to access vatic server: HTTP Error 403

### ISSUE THREAD

**Issue by siddarthsen** [jldowns/vatic-docker#1] opened 2016-10-20 20:52 UTC
Ran the follow command to download and start the vatic docker container: 
`docker run -it -p 8111:80 -v $DATA_DIR:/root/vatic/data npsvisionlab/vatic-docker /bin/bash -C /root/vatic/example.sh`

Image frames are correctly generated from video.
However, I received the following error when I navigate to http://localhost:8111
`You don't have permission to access / on this server.`

Further when I run: `turkic status --verify`
The follow test fails: 
`Testing access to web server... ERROR! HTTP Error 403: Forbidden`

**Comment by szi** [comment] 2016-10-21 15:42
Came here to submit the same issue. Looks like it's reproducible...

**Comment by jldowns** [comment] 2016-10-21 21:19
Hey thanks for pointing it out! It looks like you're using the NPSVisionLab fork of this repo located at https://github.com/NPSVisionLab/vatic-docker . Or maybe you're on the visionfork branch of this repo? (That's an upstream merge of the NPSVisionLab fork, and I'm not quite ready to incorporate all the changes yet.)

In any case, I don't control the `npsvisionlab/vatic-docker` image. My docker image is at `jldowns/vatic-docker` and the master branch README outlines how to use it. Since the Docker update a few months ago the script doesn't capture the port name and output it to the console anymore but you can find it easily enough by running `docker ps`. I haven't had the chance to fix that issue yet.

Let me know if you have any trouble running the master branch. Or maybe you can go to the NPSVisionLab page and see if they changed anything.

**Comment by kiransom** [comment] 2016-11-25 06:47
I get this same access error in both npsvision/vatic-docker and jldowns/vatic-docker.

I believe it has got to do with changes to security in docker. 
I was running on docker version 1.12.3 when I saw the access issue. I downgraded to docker version 1.6.x and the access issue was resolved. 

Here is my vagrant-based provision setup to run the vatic-docker setup with older version of docker:
https://github.com/crispyrusk/vagrantvatic

**Comment by lisaring** [comment] 2017-03-28 04:24
Forbidden

You don't have permission to access / on this server.
Apache/2.4.18 (Ubuntu) Server at localhost Port 80

same problem,  anyone solved this problem?

**Comment by jldowns** [comment] 2017-03-29 18:20
So I'm using macos Sierra and the latest Docker and I'm not hitting a problem. Did you verify that the `example.sh` script ran? It has commands in it that start the server and database. The reason I ask is that to run the command you pasted above I had to also mount the `annotation_script` directory to make `example.sh` available. You might try running `/root/vatic/startup.sh` and `sudo /etc/init.d/mysql start` inside the container to see if you can force a startup.

In other news I have some free time so I'm going to try to make this process less about "just run this monster script" and more Dockery, so maybe the problem will get resolved with a minor refactoring.

**Comment by jldowns** [comment] 2017-04-05 22:23
Hey guys, I'm going to start following the VATIC `contrib` branch at https://github.com/jldowns/vatic-docker-contrib. Since that branch is under active development and now has an official install script, I'll be using Packer to generate Docker containers from that.

Since I've changed the workflow pretty significantly (runs without a `git clone`), this repo is going to be depreciated and I'll be moving to `vatic-docker-contrib`.

**Closed as completed** 2017-04-05 22:23 UTC
